ALU/src/add_subtract_unit.sv
ALU/src/full_adder.sv
ALU/src/logic_unit.sv
ALU/src/shift_unit.sv
ALU/src/alu_mux.sv
ALU/src/decoder.sv
ALU/src/alu.sv
Instruction_Unit/src/decoder_unit.sv
Instruction_Unit/src/PC_branch.sv
Instruction_Unit/src/PC_jump.sv
Instruction_Unit/src/PC_plus.sv
Instruction_Unit/src/PC_unit.sv
Instruction_Unit/src/instruction_memory.sv
Memory/src/bit_extender.sv
Memory/src/read_data_mux.sv
Memory/src/register_file.sv
Memory/src/data_memory.sv
CPU/src/MCU_mux.sv
CPU/src/MCU.sv
CPU/src/ALUDecoder.sv
CPU/src/CPU.sv
CPU/tb/CPU_tb.sv
